info:
  app:
    name: Movie Aggregator Service

server:
  port: 8080

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: info,health,hystrix.stream
